site_name: T2D AMP Consortium Genomics Workflows on AWS
nav:
  - Overview: index.md
  - AWS resources overview:
    - Data Storage: core-env/create-s3-bucket.md
    - Compute Resources: core-env/create-custom-compute-resources.md
    - Permissions: core-env/create-iam-roles.md
    - Batch: core-env/setup-aws-batch.md
  - Containerized Tooling: containers/container-introduction.md
  - Launching Cloud Infrastructure: cloudformation-templates.md
extra_css: [extra.css]
theme: 
  name: readthedocs
  logo: 'images/logo.png'
  palette:
    primary: pink yellow
    accent: blue grey
markdown_extensions:
  - fontawesome_markdown
  - admonition
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png

repo_url: &repo_url https://github.com/T2DREAM/aws-genomics-workflows/
repo_name: Contribute
copyright: 2019 Diabetes Epigenome Atlas

plugins:
- search
- macros

extra:
  repo_url: *repo_url
  artifacts:
    s3: 
      bucket: aws-genomics-workflows
  site:
    s3:
      bucket: docs.diabetesepigenome.org
      prefix: genomics-workflows
