site_name: Genomics Workflows on AWS
nav:
  - Overview: index.md
  - CloudFormation Templates & launching infrastructure: cloudformation
  - Workflow Orchestration:
    - Cromwell:
      - Overview: orchestration/cromwell/cromwell-overview.md
      - Examples: orchestration/cromwell/cromwell-examples.md

extra_css: [extra.css]
theme: 
  name: material
  logo: 'images/logo.png'
  palette:
    primary: pink yellow
    accent: blue grey
markdown_extensions:
  - fontawesome_markdown
  - admonition
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png

repo_url: &repo_url https://github.com/T2DREAM/aws-genomics-workflows/
repo_name: Contribute
copyright: 2019 Amazon Web Services

plugins:
- search
- macros

extra:
  repo_url: *repo_url
  artifacts:
    s3: 
      bucket: aws-genomics-workflows
  site:
    s3:
      bucket: docs.t2depigenome.org
      prefix: genomics-workflows
